import 'package:flutter/material.dart';
import '../app_colors.dart';

const ColorScheme colorSchemeDark = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.primary400,
  onPrimary: Colors.white,
  primaryContainer: AppColors.primary700,
  onPrimaryContainer: AppColors.primary100,
  secondary: AppColors.secondary300,
  onSecondary: Colors.black,
  secondaryContainer: AppColors.secondary700,
  onSecondaryContainer: AppColors.secondary100,
  tertiary: AppColors.primary300,
  onTertiary: Colors.black,
  error: AppColors.error400,
  onError: Colors.black,
  errorContainer: AppColors.error700,
  onErrorContainer: AppColors.error100,
  surface: AppColors.dark50,
  onSurface: AppColors.neutral50,
  surfaceContainerHighest: AppColors.dark100,
  onSurfaceVariant: AppColors.neutral400,
  outline: Color(0xFF2E2E33),
  outlineVariant: Color(0xFF2E2E33),
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColors.neutral0,
  onInverseSurface: Color(0xFF0F0F11),
  inversePrimary: AppColors.primary500,
);
