import 'package:flutter/material.dart';
import '../app_colors.dart';

const ColorScheme colorSchemeLight = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.primary500,
  onPrimary: Colors.white,
  primaryContainer: AppColors.primary100,
  onPrimaryContainer: AppColors.primary800,
  secondary: AppColors.secondary500,
  onSecondary: Colors.white,
  secondaryContainer: AppColors.secondary100,
  onSecondaryContainer: AppColors.secondary900,
  tertiary: AppColors.primary300,
  onTertiary: AppColors.primary900,
  error: AppColors.error500,
  onError: Colors.white,
  errorContainer: AppColors.error100,
  onErrorContainer: AppColors.error700,
  surface: AppColors.neutral0,
  onSurface: Color(0xFF0F0F11),
  surfaceContainerHighest: AppColors.neutral100,
  onSurfaceVariant: AppColors.neutral500,
  outline: AppColors.neutral200,
  outlineVariant: AppColors.neutral200,
  shadow: Colors.black,
  scrim: Colors.black,
  inverseSurface: AppColors.dark50,
  onInverseSurface: AppColors.neutral50,
  inversePrimary: AppColors.primary400,
);
